config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#index'

  resources :activities

  resources :pages do
    resources :freq_infos, except: [:edit, :update]

    collection do
      get :deleted # <= this
    end

    resources :versions, only: [:destroy] do
      member do
        get :diff, to: 'versions#diff'
        patch :rollback, to: 'versions#rollback'
      end
    end
  end

  resources :versions, only: [] do
    member do
      patch :bringback  # <= and that
    end
  end

end

app/models/freq_info.rb
class FreqInfo < ActiveRecord::Base
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  belongs_to :page
  belongs_to :user
  validates :content, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :history

  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller && controller.current_user }

  has_ancestry
  has_paper_trail class_name: 'PageVersion', meta: { author_username: :user_name, word_count: :count_word }

  validates_presence_of :title, :content

  belongs_to :user
  has_many :freq_infos

  include PgSearch
  pg_search_scope :search, against: [:title, :content],
  using: {tsearch: {dictionary: "english"} }

  def self.text_search(query)
    if query.present?
       search(query)
    else
      all
    end
  end

  def count_word
    content.split(' ').count
  end




  #def self.title_search(search)
  #  if search.present?
  #     title_search(search)
  #  else
  #    all
  #  end
  #end


  #def self.title_search(search)
   # if title_search
   #   where('title LIKE ?', "%#{search}%")
   # else
   #   all
   # end
  #end

end

app/models/page_version.rb
class PageVersion < PaperTrail::Version
  self.table_name = :page_versions
  default_scope { where.not(event: 'create') }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, uniqueness: true

  has_many :pages
  has_many :freq_infos
  def self.find_version_author(version)
    find(version.terminator)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities =  PublicActivity::Activity.order("created_at desc").page(params[:page]).per_page(25)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include PublicActivity::StoreController
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActiveRecord::RecordNotFound do
    flash[:warning] = 'Resource not found.'
    redirect_back_or root_path
  end

  def redirect_back_or(path)
    redirect_to request.referer || path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/freq_infos_controller.rb
class FreqInfosController < ApplicationController
  before_action :authenticate_user!

  def create
    @page = Page.friendly.find(params[:page_id])
    freq_info = @page.freq_infos.build(freq_info_params)
    if freq_info.save
      flash[:notice] = "information saved"
      redirect_to @page
    else
      flash[:alert] = "Infomation could not be saved"
      render 'pages/show'
    end
  end

  def destroy
    @page = Page.friendly.find(params[:page_id])
    @freq_info = @page.freq_infos.find(params[:id])
    @freq_info.delete
    flash[:notice] = "Info deleted"
    redirect_to page_path
  end

  private

  def freq_info_params
    params.require(:freq_info).permit(:content).merge!(user: current_user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!#, #except: [:show, :index]
  before_filter :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.order("created_at desc").page(params[:page]).per_page(5)
    @search_results = Page.text_search(params[:query])
    @activities =  PublicActivity::Activity.order("created_at desc").limit(10)

    if params[:query]
      @queries = params[:query].split(' ')
    end
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    @page.user = current_user
    if @page.save
      flash[:notice] = "Page saved"
      redirect_to pages_path
    else
      flash[:alert] = "Page not saved"
      render :new
    end
  end

  def edit; end

  def show
    if request.path != page_path(@page)
      redirect_to @page, status: :moved_permanently
    end
    @pages = Page.all
    @freq_infos = @page.freq_infos.all.order("created_at desc")
    #@freq_info = @page.freq_infos.build
  end

  def update

    if @page.update(page_params)
      flash[:notice] = "Page updated"
      redirect_to @page
    else
      flash[:notice] = "Page was NOT updated"
      render :edit
    end
  end

  def destroy
    @page.destroy
    flash[:notice] = "Page deleted"
    redirect_to pages_path
  end

  def deleted
    @pages = PageVersion.where(event: 'destroy')
  end


  private

  def set_page
    @page = Page.friendly.find(params[:id])
  end

  def page_params
    params.require(:page).permit(:title, :content, :parent_id)
  end
end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page_and_version, only: [:diff, :rollback, :destroy]

  def diff
  end

  def rollback
    # change the current document to the specified version
    # reify gives you the object of this version
    page = @version.reify
    page.save
    redirect_to edit_page_path(page)
  end

  def bringback
    version = PageVersion.find(params[:id])
    @page = version.reify
    @page.save
    # Let's remove the version since the document is undeleted
    version.delete
    redirect_to root_path, notice: 'The page was successfully brought back!'
  end


  private

  def set_page_and_version
    @page = Page.friendly.find(params[:page_id])
    @version = @page.versions.find(params[:id])
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def highlight_query_results(content,queries)
    if queries.blank?
      content
    else
      temp = content
      queries.each do |q|
        temp.gsub!(/(#{q})/i , '<mark>\1</mark>')
      end
    end
    temp
  end

  def find_version_author_name(version)
    user = User.find_version_author(version)
    user ? user.username : ''
  end

end

app/helpers/pages_helper.rb
module PagesHelper
  def find_version_author_name(version)
    user = User.find_version_author(version)
    user ? user.username : ''
  end

  def diff(content1, content2)
    changes = Diffy::Diff.new(content1, content2,
                             include_plus_and_minus_in_html: true,
                             include_diff_info: true)
    changes.to_s.present? ? changes.to_s(:html).html_safe : 'No Changes'
  end



  #paper trail


end

app/views/activities/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h5><strong><i class="fa fa-circle-o-notch fa-spin"></i>
          All Activities</strong></h5>
      </div>

      <div class="panel-body">
        <table class="table table-striped">
          <% @activities.each do |activity| %>
            <tr><%= render_activity activity %></tr>
          <% end %>
        </table>
        <%= will_paginate @activities %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="https://www.gravatar.com/avatar/86d1bcb6609046f3535ca20691c48aa9?s=32&d=identicon&r=PG">

  <title>DocuHelp</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body data-spy="scroll" data-target="#topnav">

<body>

<nav class="navbar navbar-default navbar-fixed-top" id="topnav">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Company</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <!--   <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
       -->


      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "New Page", new_page_path %></li>
        <li><%= link_to "Activities", activities_path %></li>
        <li><%= link_to 'See Deleted Pages', deleted_pages_path %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>

          </ul>
        </li>
        <% else %>
          <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">
   <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>


<%= yield %>
</div>
</body>
</html>

app/views/pages/_form.html.erb
<h2><%= @page.new_record? ? 'Create a new page' : 'Edit page' %></h2>
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>
      <ul>
        <% @page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, size: '50', class: "form-control", placeholder: " Enter title of the page" %>
  </div> <br>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.cktext_area :content, placeholder: " Enter the page contents here" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :parent_id, "Select parent page or leave empty if create a parent page" %><br>
    <%= f.collection_select :parent_id, Page.order(:title), :id, :title, include_blank: true %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_versions.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>Index</th>

      <th>Event</th>
      <th>Word Count</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%- page.versions.reverse.each do |version| %>
      <tr>
        <td><%= version.index %></td>
        <td><%= version.event.humanize %>d by <%= find_version_author_name(version) %> <%= time_ago_in_words(version.created_at) %> ago</td>
        <td><%= version.word_count %></td>
        <td><%= link_to 'Diff', diff_page_version_path(page, version) %></td>
        <td><%= link_to 'Rollback', rollback_page_version_path(page, version), method: 'PATCH' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pages/deleted.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h5><strong><i class="fa fa-undo"></i>
          Recover Deleted Files</strong></h5>
      </div>

      <div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>ID</th>
              <th>Title</th>
              <th>Content</th>
              <th>Deleted by</th>
              <th>At</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @pages.each do |page_version| %>
              <%- page = page_version.reify %>
              <tr>
                <td><%= page.id %></td>
                <td><%= page.title %></td>
                <td><%=raw page.content %></td>
                <td><%= find_version_author_name(page_version) %></td>
                <td><%= page.created_at %></td>
                <td><%= link_to 'Bring back', bringback_version_path(page_version), method: 'PATCH' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'Back', pages_path %>
      </div>
    </div>
  </div>
</div>

app/views/pages/edit.html.erb
<%= render 'form' %>

app/views/pages/index.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h5><strong>Pages </strong> <small><%= @pages.size %></small></h5>
      </div>

      <!--<div class="panel-body text-center">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search for title...">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button">Go!</button>
          </span>
        </div>
      </div>-->

      <ul class="list-group list-group-flush">
        <% Page.roots.each do |page| %>
          <li class="list-group-item"><strong>
          <% if page.descendants.count < 1 %>
            <i class="fa fa-file-o" style="color:gray"></i>
          <% else %>
            <i class="fa fa-folder" style="color:gray"></i>
          <% end %>
          <%= link_to page.title, page %>
          <small> <%= page.descendants.count if page.descendants.count > 0 %></small>
          </strong></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-md-9">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h5><strong><i class="fa fa-bolt"></i> Quick deep search</strong></h5>
      </div>

      <div class="panel-body text-center">
        <div class="input-group">
          <div class="col-md-12">
            <%= form_tag pages_path, method: :get do %>
              <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search entire site" %>
          </div>
            <span class="input-group-btn">
              <%= submit_tag "Search", title: nil, class: "btn btn-default" %>
            </span>
            <% end %>
          </div>
      </div>
    </div>

    <% if @search_results.empty? %>
      <% if @pages.empty? %>
        You do not have any pages yet. <%= link_to "Create a New Page", new_page_path %>
      <% else %>
        <p style="color:red"><em>Could not find results for
        <% @queries.try(:each) do |q| %>
          <strong><%= q %></strong>
        <% end %>, try searching something else.</em> </p> <hr>
      <% end %>

      <% @pages.each do |page| %>
        <div class="panel panel-info">
          <div class="panel-heading">
            <h4><strong><%= link_to page.title, page %></strong></h4>
          </div>
          <div class="panel-body">
            <%=raw page.content.truncate(600) %>
          </div>
        </div>
      <% end %>

    <% elsif @queries.present? %>
      <% @search_results.try(:each) do |page| %>
       <div class="panel panel-info">
        <div class="panel-heading">
          <h4><strong><%= link_to page.title, page %></strong></h4>
        </div>
        <div class="panel-body">
          <%=raw highlight_query_results(page.content, @queries) %>
        </div>
      </div>
     <% end %>

    <% else %>

    <div class="panel panel-info">
      <div class="panel-heading">
        <h5><strong><i class="fa fa-circle-o-notch fa-spin"></i> Recent Activities</strong></h5>
      </div>

      <div class="panel-body">
        <table class="table table-striped">
          <% @activities.each do |activity| %>
            <tr><%= render_activity activity %></tr>
          <% end %>
        </table>
      </div>
    <% end %>
  </div>
    <%= button_to "more activities", activities_path, method: :get, class: "btn btn-default btn-block"  %>
</div>

app/views/pages/new.html.erb
<%= render 'form' %>

app/views/pages/show.html.erb
<div class="row">
  <div class="col-md-3">

    <% if @page.parent.present? %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h5><strong>Parent page</strong></h5>
        </div>
        <ul class="list-group list-group-flush">
          <strong><li class="list-group-item"><i class="fa fa-folder-o"></i>
            <%= link_to @page.parent.title, @page.parent %></li>
          </strong>
        </ul>
      </div>
    <% end %>

    <% if @page.descendants.present? %>
      <div class="panel panel-info">
        <div class="panel-heading">
          <h5><strong>Subpages </strong> <small><%= @page.descendants.size %></small></h5>
        </div>
        <ul class="list-group list-group-flush">
          <% @page.descendants.each do |page| %>
            <strong><li class="list-group-item"><i class="fa fa-file-o" style="color:gray"></i>
            <%= link_to page.title, page %></li>
            </strong>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="panel panel-info">
      <div class="panel-heading">
        <h5><strong>Frequently requested info </strong></h5>
      </div>
      <ul class="list-group list-group-flush">
        <% @freq_infos.each do |info|%>
          <li class="list-group-item">
          <%= info.content %>
          <%= link_to [@page, info, @freq_info], :method => :delete, data: { confirm: 'Are you sure?' },  :action => "destroy", :commit =>"destroy" do  %>
          <i class="fa fa-trash-o" style="color:gray"></i>
          <% end %></li>
        <% end %>

        <%= form_for [@page, FreqInfo.new]  do |f| %>
          <div class="panel-body text-center">
            <div class="input-group">
              <div class="col-12">
                <%= f.text_field :content, class: "form-control", type: "text", placeholder: "Add a quick info" %>
              </div>
              <span class="input-group-btn">
                <%= f.submit "Add!", class: "btn btn-default" %>
              </span>
            </div>
          </div>
        <% end %>
      </ul>
    </div>

    <div class="panel panel-info">
      <div class="panel-heading">
        <h5><strong>Page info </strong></h5>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
        Created on <small><%= "#{@page.created_at.strftime("#{@page.created_at.day.ordinalize} %B, %Y")}" %></small></li>

        <% if !@page.versions.empty? %>
          <li class="list-group-item">
          Updated:<small> <%= "#{@page.updated_at.strftime("#{@page.updated_at.day.ordinalize} %B, %Y")}" %> <br>
          <em>by <%= User.find_by_id(@page.versions.last.whodunnit).username %></small></em></li>
        <% end %>
        <li class="list-group-item">
          <%= link_to 'Edit Page', edit_page_path(@page) %> | <%= link_to 'Delete Page', @page, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
  </div>

  <div class="col-md-9">

    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#page" aria-controls="page" role="tab" data-toggle="tab">Inner search</a></li>
      <% if !@page.versions.empty? %>
        <li role="presentation"><a href="#version" aria-controls="version" role="tab" data-toggle="tab">Previous versions <small>( <%= @page.versions.count %> )</small></a></li> <% end %>
        <li role="presentation"><a href="#site" aria-controls="site" role="tab" data-toggle="tab">Outer search</a></li>
    </ul>

    <div class="tab-content">

      <div role="tabpanel" class="tab-pane active" id="page">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h5><strong><i class="fa fa-sticky-note"></i> Search within this page</strong></h5>
          </div>

          <div class="panel-body text-center">
            <div class="input-group">
              <div class="col-md-12">
                <input type="text" class="form-control" placeholder="Keywords will be highlighted" id="word-search">
              </div>

              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="version">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h5><strong><i class="fa fa-server"></i></i> Previous versions of this page</strong></h5>
          </div>
          <div class="col-md-12">
            <%= render 'versions', page: @page %>
          </div>
        </div>
      </div>


      <div role="tabpanel" class="tab-pane" id="site">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h5><strong><i class="fa fa-bolt"></i> Search the entire site</strong></h5>
          </div>
          <div class="panel-body text-center">
            <div class="input-group">
              <div class="col-md-12">
                <%= form_tag pages_path, method: :get do %>
                  <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Search entire site" %>
              </div>
                  <span class="input-group-btn">
                    <%= submit_tag "Search", title: nil, class: "btn btn-default" %>
                  </span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

    <div class="panel panel-info">
      <div class="panel-heading">
        <h4><strong><%= @page.title %></strong></h4>
      </div>
      <div class="panel-body">
        <%=raw @page.content %>
      </div>
    </div>
  </div>
</div>

app/views/public_activity/freq_info/_create.html.erb
<td><i class="fa fa-info-circle fa-2x" style="color:gray"></i></td>
<td><small> <%= time_ago_in_words(activity.created_at) %> ago</small> <br>
  <% if activity.trackable %>
    <%= activity.owner.username if activity.owner %>
    <strong>added</strong> a frequently requested info to the page:
    <strong><%= link_to activity.trackable.page.title, activity.trackable.page %></strong>
  <% else %>
    A frequently requested info was deleted by <strong><%= activity.owner.username if activity.owner %>.</strong>
  <% end %>
</td>

app/views/public_activity/freq_info/_destroy.html.erb
<td><i class="fa fa-info-circle fa-2x" style="color:gray"></i></td>
<td><small> <%= time_ago_in_words(activity.created_at) %> ago</small> <br>
  <% if activity.trackable %>
    <%= activity.owner.username if activity.owner %>
    <strong>deleted</strong> a frequently requested info page:
    <strong><%= link_to activity.trackable.page.title, activity.trackable.page %></strong>
  <% else %>
    A frequently requested info was deleted by <%= activity.owner.username if activity.owner %>.
  <% end %>
</td>

app/views/public_activity/freq_info/_update.html.erb
<td><i class="fa fa-info-circle fa-2x" style="color:gray"></i></td>
<td><small> <%= time_ago_in_words(activity.created_at) %> ago</small> <br>
  <% if activity.trackable %>
    <%= activity.owner.username if activity.owner %>
    <strong>updated</strong> a frequently requested info on the page:
    <strong><%= link_to activity.trackable.page.title, activity.trackable.page %></strong>
  <% else %>
    A frequently requested info was deleted by <%= activity.owner.username if activity.owner %>.
  <% end %>
</td>

app/views/public_activity/page/_create.html.erb
<td><i class="fa fa-book fa-2x" style="color:gray"></i></td>
<td><small> <%= time_ago_in_words(activity.created_at) %> ago</small> <br>
  <% if activity.trackable %>
    <%= activity.owner.username if activity.owner %>
    <strong>created</strong> a page title:
    <strong><%= link_to activity.trackable.title, activity.trackable if activity.trackable.title%></strong>
  <% else %>
    A file was deleted by <%= activity.owner.username if activity.owner %>.<%= link_to ' Click here to learn more or recover the file', deleted_pages_path %>
  <% end %>
</td>

app/views/public_activity/page/_destroy.html.erb
<td><i class="fa fa-trash fa-2x" style="color:gray"></i></td>
<td><small> <%= time_ago_in_words(activity.created_at) %> ago</small> <br>
  <% if activity.trackable %>
    <%= activity.owner.username if activity.owner %>
    <strong>deleted <em>but brought back</em> the page titled:</strong>
    <strong><%= link_to activity.trackable.title, activity.trackable %></strong>
  <% else %>
    A file was deleted by <%= activity.owner.username if activity.owner %>.<%= link_to ' Click here to learn more or recover the file', deleted_pages_path %>
  <% end %>
</td>

app/views/public_activity/page/_update.html.erb
<td><i class="fa fa-pencil-square-o fa-2x" style="color:gray"></i></td>
<td><small> <%= time_ago_in_words(activity.created_at) %> ago</small> <br>
  <% if activity.trackable %>
    <%= activity.owner.username if activity.owner %>
    <strong>updated</strong> the page:
    <strong><%= link_to activity.trackable.title, activity.trackable %></strong>
  <% else %>
    A file was deleted by <%= activity.owner.username if activity.owner %>.<%= link_to ' Click here to learn more or recover the file', deleted_pages_path %>
  <% end %>
</td>

app/views/versions/diff.html.erb
<div class='row mt'>
  <div class='col-sm-12'>
    <h2><%= "Diff between Version #{@version.id} and Current Version" %></h2>
    <style><%= Diffy::CSS %></style>
    <div class='well diff'>
      <p>
        <strong>Title:</strong>
        <%= diff(@version.reify.title, @page.title) %>
      </p>
      <p>
        <strong>Content:</strong>
        <%= diff(@version.reify.content, @page.content) %>
      </p>
    </div>
    <p>
    <%= "'#{@version.event.humanize}' by #{find_version_author_name(@version)} on #{@version.created_at.strftime("#{@version.created_at.day.ordinalize} of %B, %Y at %I:%M %p EST")}." %> <br>
    </p>
  </div>
</div>
<div class='fr'>
  <%= link_to 'Back', edit_page_path(@page), class: 'btn btn-danger' %>
  <%= link_to 'Rollback', rollback_page_version_path(@page, @version), class: 'btn btn-primary', method: 'PATCH' %>
</div>